### PR TITLE
Setup travis

### PR DESCRIPTION
**Pull request by axel3rd**

### CODE REVIEW

**Comment by axel3rd** [comment]
Nice ! 😀

**Comment by Transrian** [comment]
Yes :smile: 
Even if it's only integration tests, now should be easier to do the unit tests !
This branch is good for now, should I do a Squash on this one to *not polute* master ?
(I'm not used to squash / rebase yet)

**Comment by axel3rd** [comment]
> should I do a Squash on this one to not polute master ?

I think yes

**Comment by Transrian** [comment]
Ok, two last for today, and here we go!
Thanks for everything :smiley:

**Pull request merged**
